### ISSUE TITLE
SampleRatio class not working for sample sizes below 1000

### ISSUE THREAD

**Issue by oleolegka** [e10v/tea-tasting#69]
https://github.com/e10v/tea-tasting/blob/e80d704c0dcb2053ba23ca24e5d36c18909612f4/src/tea_tasting/metrics/proportion.py#L153
[scipy.stats.binomtest](https://github.com/scipy/scipy/blob/dde50595862a4f9cede24b5d1c86935c30f1f88a/scipy/stats/_binomtest.py#L287) requires that both k and n must be int, but 
```
 k = aggr[treatment].count()
 n = k + aggr[control].count()
```
returns float

**Comment by e10v** [comment]
Fixed in https://github.com/e10v/tea-tasting/pull/73. I'll close the issue after release of the next version.

**Comment by e10v** [comment]
Released fix in the latest version: https://github.com/e10v/tea-tasting/releases/tag/v0.1.0
